from __future__ import annotations

import copy
import os
import re
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
from dotenv import dotenv_values

from tradingagents.default_config import DEFAULT_CONFIG
from tradingagents.web.store import RunStore

STAGES = ("analysts", "research", "trader", "risk", "portfolio_manager")
REPORT_KEYS = (
    "market_report",
    "sentiment_report",
    "news_report",
    "fundamentals_report",
    "investment_debate_state",
    "investment_plan",
    "trader_investment_plan",
    "risk_debate_state",
    "final_trade_decision",
)


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _extract_field(text: Any, label: str) -> str:
    if not isinstance(text, str):
        return ""
    match = re.search(
        rf"\*\*{re.escape(label)}\*\*\s*:\s*(.*?)(?=\n\s*\*\*[^*]+\*\*\s*:|\Z)",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return match.group(1).strip() if match else ""


def _as_float(value: str) -> float | None:
    match = re.search(r"-?\d+(?:,\d{3})*(?:\.\d+)?", value or "")
    if not match:
        return None
    return float(match.group(0).replace(",", ""))


def _safe_error(exc: Exception) -> str:
    message = str(exc).strip() or exc.__class__.__name__
    message = re.sub(
        r"(?i)(api[_-]?key|token|password|secret)=([^&\s]+)",
        r"\1=[redacted]",
        message,
    )
    message = re.sub(r"(?i)bearer\s+\S+", "Bearer [redacted]", message)
    return message[:1000]


def build_structured_result(
    *,
    final_state: dict[str, Any],
    decision: str,
    request: dict[str, Any],
    data_sources: dict[str, Any],
) -> dict[str, Any]:
    trader_text = final_state.get("trader_investment_plan", "")
    portfolio_text = final_state.get("final_trade_decision", "")
    reports = {key: final_state.get(key) for key in REPORT_KEYS if key in final_state}

    return {
        "signal": decision,
        "trader_proposal": {
            "action": _extract_field(trader_text, "Action") or decision,
            "reasoning": _extract_field(trader_text, "Reasoning"),
            "entry_price": _as_float(_extract_field(trader_text, "Entry Price")),
            "stop_loss": _as_float(_extract_field(trader_text, "Stop Loss")),
            "position_sizing": _extract_field(trader_text, "Position Sizing"),
        },
        "portfolio_decision": {
            "rating": _extract_field(portfolio_text, "Rating") or decision,
            "executive_summary": _extract_field(portfolio_text, "Executive Summary"),
            "investment_thesis": _extract_field(portfolio_text, "Investment Thesis"),
            "price_target": _as_float(_extract_field(portfolio_text, "Price Target")),
            "time_horizon": _extract_field(portfolio_text, "Time Horizon"),
        },
        "reports": reports,
        "model_route": request.get("model_route", "local_5090"),
        "model": {
            "provider": request.get("llm_provider", ""),
            "quick": request.get("quick_think_llm", ""),
            "deep": request.get("deep_think_llm", ""),
        },
        "data_sources": data_sources,
        "analysis_date": request.get("analysis_date"),
        "completed_at": _utc_now(),
        "broker_execution": False,
        "risk_notice": (
            "Research output only. Prices, targets and language generated by the "
            "model must not be used directly as executable broker instructions."
        ),
    }


def resolve_local_model_settings(request: dict[str, Any]) -> dict[str, str]:
    workbench_values: dict[str, Any] = {}
    workbench_env_file = os.getenv("TRADINGAGENTS_WORKBENCH_ENV_FILE", "").strip()
    if workbench_env_file:
        workbench_values = dotenv_values(workbench_env_file)

    backend_url = (
        str(request.get("backend_url") or "").strip()
        or os.getenv("TRADINGAGENTS_LOCAL_LLM_BASE_URL", "").strip()
        or os.getenv("TRADINGAGENTS_LLM_BACKEND_URL", "").strip()
        or str(workbench_values.get("AI_WORKBENCH_LOCAL_LLM_BASE_URL") or "").strip()
    )
    default_model = (
        os.getenv("TRADINGAGENTS_LOCAL_MODEL", "").strip()
        or str(workbench_values.get("AI_WORKBENCH_LOCAL_LLM_MODEL") or "").strip()
    )
    quick_model = (
        str(request.get("quick_think_llm") or "").strip()
        or os.getenv("TRADINGAGENTS_LOCAL_QUICK_MODEL", "").strip()
        or default_model
        or DEFAULT_CONFIG["quick_think_llm"]
    )
    deep_model = (
        str(request.get("deep_think_llm") or "").strip()
        or os.getenv("TRADINGAGENTS_LOCAL_DEEP_MODEL", "").strip()
        or default_model
        or DEFAULT_CONFIG["deep_think_llm"]
    )
    api_key = str(
        workbench_values.get("AI_WORKBENCH_LOCAL_LLM_API_KEY") or ""
    ).strip()
    if api_key and not os.getenv("OPENAI_COMPATIBLE_API_KEY"):
        os.environ["OPENAI_COMPATIBLE_API_KEY"] = api_key
    return {
        "backend_url": backend_url,
        "quick_think_llm": quick_model,
        "deep_think_llm": deep_model,
    }


def local_model_readiness(
    request: dict[str, Any],
    *,
    request_get: Callable[..., Any] = requests.get,
    timeout_seconds: float = 5.0,
) -> dict[str, Any]:
    settings = resolve_local_model_settings(request)
    backend_url = settings["backend_url"].rstrip("/")
    result = {
        "status": "unconfigured",
        "reachable": False,
        "model_route": "local_5090",
        "model": settings["quick_think_llm"],
        "message": (
            "Local 5090 model endpoint is not configured. Set "
            "TRADINGAGENTS_LOCAL_LLM_BASE_URL."
        ),
    }
    if not backend_url:
        return result

    headers = {}
    api_key = os.getenv("OPENAI_COMPATIBLE_API_KEY", "").strip()
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    try:
        response = request_get(
            f"{backend_url}/models",
            headers=headers,
            timeout=timeout_seconds,
        )
        status_code = int(getattr(response, "status_code", 0))
        if not 200 <= status_code < 300:
            return {
                **result,
                "status": "unavailable",
                "message": (
                    "Configured 5090 model endpoint responded with "
                    f"HTTP {status_code}."
                ),
            }
    except requests.Timeout:
        return {
            **result,
            "status": "unavailable",
            "message": (
                "Configured 5090 model endpoint did not respond within "
                f"{timeout_seconds:g} seconds. Restore the 5090 service or "
                "manually choose a cloud route."
            ),
        }
    except requests.RequestException:
        return {
            **result,
            "status": "unavailable",
            "message": (
                "Configured 5090 model endpoint is unreachable. Restore the "
                "5090 service or manually choose a cloud route."
            ),
        }

    return {
        **result,
        "status": "ready",
        "reachable": True,
        "message": "Configured 5090 model endpoint is ready.",
    }


class TradingAgentsAnalysisEngine:
    def __init__(self, output_dir: Path | str):
        self.output_dir = Path(output_dir)

    def run(
        self,
        request: dict[str, Any],
        on_progress: Callable[[str, dict[str, Any]], None],
    ) -> tuple[dict[str, Any], str, dict[str, Any]]:
        config = copy.deepcopy(DEFAULT_CONFIG)
        route = request.get("model_route", "local_5090")
        backend_url = str(request.get("backend_url") or "").strip()

        if route == "local_5090":
            readiness = local_model_readiness(request)
            if readiness["status"] != "ready":
                raise RuntimeError(readiness["message"])
            local_settings = resolve_local_model_settings(request)
            backend_url = local_settings["backend_url"]
            config["llm_provider"] = "openai_compatible"
        else:
            if not request.get("cloud_confirmed"):
                raise RuntimeError("Cloud model route requires explicit confirmation.")
            config["llm_provider"] = request.get("llm_provider") or config["llm_provider"]

        config["backend_url"] = backend_url or config.get("backend_url")
        if route == "local_5090":
            config["quick_think_llm"] = local_settings["quick_think_llm"]
            config["deep_think_llm"] = local_settings["deep_think_llm"]
        else:
            config["quick_think_llm"] = (
                request.get("quick_think_llm") or config["quick_think_llm"]
            )
            config["deep_think_llm"] = (
                request.get("deep_think_llm") or config["deep_think_llm"]
            )
        config["max_debate_rounds"] = int(request.get("debate_rounds", 1))
        config["max_risk_discuss_rounds"] = int(request.get("debate_rounds", 1))
        config["output_language"] = request.get("output_language") or "Chinese"
        config["checkpoint_enabled"] = bool(request.get("checkpoint_enabled", True))
        config["results_dir"] = str(self.output_dir / "logs")
        config["data_cache_dir"] = str(self.output_dir / "cache")
        config["memory_log_path"] = str(self.output_dir / "memory" / "trading_memory.md")

        from tradingagents.graph.trading_graph import TradingAgentsGraph

        on_progress("analysts", {})
        graph = TradingAgentsGraph(
            selected_analysts=request.get("analysts")
            or ["market", "social", "news", "fundamentals"],
            config=config,
        )
        final_state, decision = graph.propagate(
            request["ticker"],
            request["analysis_date"],
        )
        on_progress("research", final_state)
        on_progress("trader", final_state)
        on_progress("risk", final_state)
        on_progress("portfolio_manager", final_state)
        return final_state, decision, copy.deepcopy(config["data_vendors"])


def execute_run(
    store: RunStore,
    run_id: str,
    request: dict[str, Any],
    *,
    engine: Any | None = None,
) -> None:
    analysis_engine = engine or TradingAgentsAnalysisEngine(store.root / run_id / "artifacts")
    stages = dict.fromkeys(STAGES, "pending")
    reports: dict[str, Any] = {}

    def on_progress(stage: str, payload: dict[str, Any]) -> None:
        if stage not in stages:
            return
        stage_index = STAGES.index(stage)
        for index, name in enumerate(STAGES):
            if index < stage_index:
                stages[name] = "completed"
            elif index == stage_index:
                stages[name] = "running"
        for key in REPORT_KEYS:
            if key in payload:
                reports[key] = payload[key]
        store.update(
            run_id,
            status="running",
            progress={"current_stage": stage, "stages": dict(stages)},
            reports=reports,
        )

    store.update(
        run_id,
        status="running",
        progress={"current_stage": "starting", "stages": dict(stages)},
    )
    try:
        final_state, decision, data_sources = analysis_engine.run(request, on_progress)
        result = build_structured_result(
            final_state=final_state,
            decision=decision,
            request=request,
            data_sources=data_sources,
        )
        store.update(
            run_id,
            status="succeeded",
            progress={
                "current_stage": "completed",
                "stages": dict.fromkeys(STAGES, "completed"),
            },
            reports=result["reports"],
            result=result,
            error="",
        )
    except Exception as exc:
        store.update(
            run_id,
            status="failed",
            progress={
                "current_stage": "failed",
                "stages": dict(stages),
            },
            error=_safe_error(exc),
        )


class ThreadedRunDispatcher:
    def __init__(self, store: RunStore, max_workers: int = 1):
        self.store = store
        self.executor = ThreadPoolExecutor(
            max_workers=max_workers,
            thread_name_prefix="tradingagents-web",
        )

    def submit(self, run_id: str, request: dict[str, Any]) -> None:
        self.executor.submit(execute_run, self.store, run_id, request)
